export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'


export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'

export const PRODUCT_ADD_BID_REQUEST = 'PRODUCT_ADD_BID_REQUEST'
export const PRODUCT_ADD_BID_SUCCESS = 'PRODUCT_ADD_BID_SUCCESS'
export const PRODUCT_ADD_BID_FAIL = 'PRODUCT_ADD_BID_FAIL'
export const PRODUCT_ADD_BID_RESET = 'PRODUCT_ADD_BID_RESET'

export const GET_ACTIVE_PRODUCTS_REQUEST = 'GET_ACTIVE_PRODUCTS_REQUEST'
export const GET_ACTIVE_PRODUCTS_SUCCESS = 'GET_ACTIVE_PRODUCTS_SUCCESS'
export const GET_ACTIVE_PRODUCTS_FAIL = 'GET_ACTIVE_PRODUCTS_FAIL'
export const GET_ACTIVE_PRODUCTS_RESET = 'GET_ACTIVE_PRODUCTS_RESET'

export const GET_INACTIVE_PRODUCTS_REQUEST = 'GET_INACTIVE_PRODUCTS_REQUEST'
export const GET_INACTIVE_PRODUCTS_SUCCESS = 'GET_INACTIVE_PRODUCTS_SUCCESS'
export const GET_INACTIVE_PRODUCTS_FAIL = 'GET_INACTIVE_PRODUCTS_FAIL'
export const GET_INACTIVE_PRODUCTS_RESET = 'GET_INACTIVE_PRODUCTS_RESET'


export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
