export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'
export const GET_REVIEWS_RESET = 'GET_REVIEWS_RESET'

export const USER_CREATE_REVIEW_REQUEST = 'USER_CREATE_REVIEW_REQUEST'
export const USER_CREATE_REVIEW_SUCCESS = 'USER_CREATE_REVIEW_SUCCESS'
export const USER_CREATE_REVIEW_FAIL = 'USER_CREATE_REVIEW_FAIL'
export const USER_CREATE_REVIEW_RESET = 'USER_CREATE_REVIEW_RESET'

export const MAKE_HELPFUL_REVIEW_REQUEST = 'MAKE_HELPFUL_REVIEW_REQUEST'
export const MAKE_HELPFUL_REVIEW_SUCCESS = 'MAKE_HELPFUL_REVIEW_SUCCESS'
export const MAKE_HELPFUL_REVIEW_FAIL = 'MAKE_HELPFUL_REVIEW_FAIL'
export const MAKE_HELPFUL_REVIEW_RESET = 'MAKE_HELPFUL_REVIEW_RESET'
